import{i}from"./assets/vendor-ad859c2f.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const c="42772780-849d5e67a8b9b0ab7e6b7483b",l=`https://pixabay.com/api/?key=${c}&image_type=photo&orientation=horizontal&safesearch=true`,u={async fetchImages(e){try{const r=await fetch(`${l}&q=${encodeURIComponent(e)}`);if(!r.ok)throw new Error("Failed to fetch images");return(await r.json()).hits}catch(r){throw console.error("Error fetching images:",r),handleError(r),r}}};function f(e){const r=document.querySelector(".gallery");if(!r){console.error("Gallery list not found");return}if(r.innerHTML="",e.length===0){i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"});return}const n=e.map(s=>`
      <li class="gallery-item">
        <a href="${s.largeImageURL}" class="gallery-link">
          <img
            src="${s.webformatURL}"
            alt="${s.tags}"
            class="gallery-image"
          />
        </a>
      </li>
    `).join("");r.innerHTML=n}function d(){const e=document.querySelector(".loader");e?e.classList.add("visible"):console.error("Loader not found")}function m(){const e=document.querySelector(".loader");e?e.classList.remove("visible"):console.error("Loader not found")}function y(e){console.error("Error:",e),h("An error occurred. Please try again later.")}function h(e){i.error({title:"Error",message:e})}function g(e){i.warning({title:"Warning",message:e})}const p=document.querySelector(".search-form"),L=document.querySelector(".search-input");p.addEventListener("submit",async e=>{e.preventDefault();const r=L.value.trim();if(r===""){g("Please enter a search query!");return}d();try{const n=await u.fetchImages(r);f(n)}catch(n){y(n)}finally{m()}});
//# sourceMappingURL=commonHelpers.js.map
